name: Prueba instalador helm

on:
  workflow_dispatch:

jobs:
  instalar-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
      
      - name: Instalar helmfile
        uses: mamezou-tech/setup-helmfile@v1.3.0
        with:
          helmfile-version: v0.159.0
          helm-version: v3.13.3
          additional-helm-plugins: https://github.com/jkroepke/helm-secrets --version v4.5.1

      - name: Instalar sops
        run: |
          wget -O /home/runner/bin/sops https://github.com/getsops/sops/releases/download/v3.8.1/sops-v3.8.1.linux.amd64
          chmod +x /home/runner/bin/sops
      
      - name: Test instalaciones
        run: |
          echo "Version kubectl"
          kubectl version --client
          echo "Version helm"
          helm version
          echo "Version helmfile"
          helmfile version
          echo "Version de helm secrets"
          helm secrets -v
          echo "Version de sops"
          sops --version
