name: Prueba instalador helm

on:
  workflow_dispatch:

jobs:
  instalar-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
      
      - name: Instalar helmfile
        uses: mamezou-tech/setup-helmfile@v1.3.0
        with:
          helmfile-version: v0.159.0
          helm-version: v3.13.3

      - name: Test instalaciones
        run:
          kubectl version --client
          helm version
          helmfile --version
